### PR TITLE
Use npm files, closes #595

### LINKED ISSUE #595: Make use of `files` to clean up the NPM package
[`package.json`](https://docs.npmjs.com/files/package.json#files) offers `files` key that allows the distributed NPM package to exclude things like source code, release scripts and other assets.

Right now NPM package is full of everything required to _work_ on `branch-sdk`, but it looks like the only things required for running it are contained to the `dist/` directory.

### PR DESCRIPTION
**Pull request by brendo**
Using `npm pack`: 

Before:

```
npm notice === Tarball Details === 
npm notice name:          branch-sdk                              
npm notice version:       2.40.0                                  
npm notice filename:      branch-sdk-2.40.0.tgz                   
npm notice package size:  333.0 kB                                
npm notice unpacked size: 955.7 kB                                
npm notice shasum:        e3252e8febdbfb6cdb5a7778a4eca08483841828
npm notice integrity:     sha512-NEa6pVwzarBZ2[...]0D5FHhL0a+lIA==
npm notice total files:   84   
```

After:

```
npm notice === Tarball Details === 
npm notice name:          branch-sdk                              
npm notice version:       2.40.0                                  
npm notice filename:      branch-sdk-2.40.0.tgz                   
npm notice package size:  73.2 kB                                 
npm notice unpacked size: 268.6 kB                                
npm notice shasum:        f4d27b968e4de15c46110954b398950a2f4cc106
npm notice integrity:     sha512-Kbtia8hW/y3w0[...]ELO/3sMdOeE1w==
npm notice total files:   6    
```

Closes #595

### CODE REVIEW

**Comment by brendo** [comment]
@yntema @rubinsingh is this useful?

**Comment by rubinsingh** [comment]
@brendo thanks for creating this PR! We're going to evaluate/test your change once we've successfully deployed at least once using our new Circle CI 2 deployment process. Moving from Circle CI 1 to Circle CI 2 is a big change so we'd like to have a deploy complete successfully before modifying the deployment process with this change.

**Comment by brendo** [comment]
Understandable, we just experienced the same migration 😄

**Comment by brendo** [comment]
Now that the Circle 2 migration has happened, #609, could this be looked at again?

**Pull request closed without merging**
