### PR TITLE
INTENG-12729: Sticky Interstitial Full Page

### PR DESCRIPTION
**Pull request by wwest-branch**
Adding overflow:hidden styling to .branch-banner-no-scroll, which is removed when user clicks to remove interstitial.

https://branch.atlassian.net/browse/INTENG-12729

### CODE REVIEW

**Review by jdee — COMMENTED** [review]
Looks good, but we should add unit tests. You can run them in a browser by opening test/test.html.

**Comment by wwest-branch** [comment]
> Looks good, but we should add unit tests. You can run them in a browser by opening test/test.html.

After looking through this with Joerg, we concluded that the animateBannerExit function would need to be heavily refactored for us to unit test this code change. As I mentioned to you earlier, the setTimeout inside of animateBannerExit never gets invoked inside of the unit test, and there are a lot of cases inside of animateBannerExit that could be preventing this from happening. That said, we do have a branch-micro test plan and are writing integration tests for this. @jwangler-branch

**Comment by wwest-branch** [comment]
> Looks good, but we should add unit tests. You can run them in a browser by opening test/test.html.

Please disregard the comment above, I was able to add some unit tests.

**Comment by jwangler-branch** [comment]
Ah, you figured it out 👍

**Comment by wwest-branch** [comment]
> Ah, you figured it out 👍

Yea, @yli-branch  pointed me to using sinon fake timers which was able to get past the setTimeout. However, you are right in that there is a lot of other logic that we needed to account for, which made this a lot harder. A refactor breaking animateBannerExit into smaller functions will be a good project in the future.

**Review by jdee — APPROVED** [review]
Looks good. We can address further refactoring later. Thanks.

**Pull request merged**
