### PR TITLE
[minor] BUX-2354 change not to focus entire banner div box

### PR DESCRIPTION
**Pull request by hana-branch**
# Pull Request Template

## Description
change not to focus the entire banner div box so yellow box-shadow does not around the banner 

Fixes # https://branch.atlassian.net/browse/BUX-2354

## Type of change

Please delete options that are not relevant.
- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Unit test
- [X] Integration test

## JS Budget Check

Please mention the size in kb before abd after this PR

| Files            | Before      | After       | 
| -----------      | ----------- | ----------- |
| dist/build.js.   |    164 KB         |    164 KB         |
| dist/build.min.js|   74 KB	          |   74 KB	         |

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Mentions: 
List the person or team responsible for reviewing proposed changes.

cc @BranchMetrics/saas-sdk-devs for visibility.

### CODE REVIEW

**Comment by JagadeeshKaricherla-branch** [comment]
build.js, build.min.js changes look incorrect and breaking.

You can either generate them correctly using `make release` or totally remove them from the PR.

**Comment by hana-branch** [comment]
@JagadeeshKaricherla-branch `make release` does not change anything and then I try to copy and current master to dist file but it still shows a difference. can you please suggest me how can I handle this?

**Comment by JagadeeshKaricherla-branch** [comment]
@hana-branch no need to push build.js, build.min.js

**Comment by hana-branch** [comment]
@JagadeeshKaricherla-branch I generated the new PR here: https://github.com/BranchMetrics/web-branch-deep-linking-attribution/pull/899 . Please review that PR?

**Pull request closed without merging**
